### ISSUE TITLE
The red string in the start log: (E) CPU Does not support AVX2. Extension plugin NOT loading!

### ISSUE THREAD

**Issue by sergsero** [altillimity/SatDump#231]
Hello,
Including the last commit I get the red string in the start log:
`"[01/04/23 - 13:30:14] ( E) CPU Does not support AVX2. Extension plugin NOT loading!"`.
But the next line reports: `"[01/04/23 - 13:30:14] ( T) Plugin simd_avx2 loaded!"`.
![20230104_start_log_error](https://user-images.githubusercontent.com/4005442/210513978-0696ac6a-8f89-41cc-a287-a9dd51c52df3.png)

The file build/CMakeCache.txt also contains messages (also for block C) that AVX2 has been found and will be used during compilation.
![20230104_CMakeCache txt-CXX](https://user-images.githubusercontent.com/4005442/210514142-2999e96d-487b-4832-a067-cc723e61028f.png)

What could be causing this red line's issue?

System: ubuntu 22.04, core 5.15.0-56-generic, cpu i9-11900K.
p.s. In another case I also tried using the --native option when compiling, but the result is the same.

Sincerely,
sergsero

**Comment by Aang23** [comment]
Actually, this is not an error and exactly what should happen!

CMake tests if the compiler (GCC) is able to compile AVX2 code. If it's x86, it pretty much always can. Hence, the plugin is compiled. When SatDump starts, the plugin is loaded and checks if the current CPU support it. If it doesn't, this message is shown and no AVX2 code is loaded.  And if it does, it is loaded and used.

This is done this way to make AVX2/SSE etc utilization non-dependent on the system it was built on, since that is not always a guarantee.

Hopefully clarifies things.
