### ISSUE TITLE
Auto-builds

### ISSUE THREAD

**Issue by berryempire** [altillimity/SatDump#84]
Github Actions can be used to auto-build binaries like .exe .deb, etc.
Please utilize it. Thanks!

**Comment by ZbychuButItWasTaken** [comment]
Hi
We're already using Github Actions to generate Windows and Android builds.

**Comment by Aang23** [comment]
Indeed, it has been done for a while.

.deb files are not currently generated mostly because I didn't get around to setting up CPack just yet. Otherwise, I would generate .debs for common distributions.

What were you thinking about exactly? If it's .exe, then this issue can closed, otherwise, .deb is valid and I'd reopen it.

**Comment by berryempire** [comment]
Hello, I'm using Ubuntu and auto-built .deb binaries would make the process of installation much simpler.
Thanks!

**Comment by berryempire** [comment]
@Aang23 Ubuntu 21.1

**Comment by AlexandreRouma** [comment]
@Aang23 I can PR the same system I use for SDR++ if you want. (for the RPi builds you'll need a pi configured to as a github actions worker)

**Comment by berryempire** [comment]
@Aang23 @ZbychuButItWasTaken Would it be possible, please?

**Comment by ZbychuButItWasTaken** [comment]
Sure, we can put it in the TODO
